config/routes.rb
Rails.application.routes.draw do
  get 'meal_assignment/index'
  get 'meal_assignment', to: 'meal_assignment#index'

  get 'user/index'
  resources :user do
    member do
      get 'preference', to: 'preference#new'
      get 'preference/new'
      get 'preference/edit'
      put 'preference/update'

      get 'meal/show'
      get 'meal', to: 'meal#show'
    end
  end

  devise_for :users
  root 'home#index'
  get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :user
  belongs_to :meal_availability
end

app/models/meal_availability.rb
class MealAvailability < ApplicationRecord
  has_many :meals

  before_save :default_value

  def default_value
    self.chicken ||= 0
    self.mutton ||= 0
    self.beef ||= 0
    self.fish ||= 0
    self.prawn ||= 0
    self.squid ||= 0
  end

  def total
    chicken + mutton + beef + fish + prawn + squid
  end
end

app/models/preference.rb
class Preference < ApplicationRecord
  belongs_to :user

  def to_array
    preferences = []

    preferences << 'chicken' if self.chicken?
    preferences << 'mutton' if self.mutton?
    preferences << 'beef' if self.beef?
    preferences << 'fish' if self.fish?
    preferences << 'prawn' if self.prawn?
    preferences << 'squid' if self.squid?

    preferences
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :preference
  has_many :meals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    user_index_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/meal_assignment_controller.rb
class MealAssignmentController < ApplicationController
  def index
    service = MealAssignmentService.new
    @meal_availability = service.generate_meal_availability(User.count)
    service.meal_assignment(User.all)
  end
end

app/controllers/meal_controller.rb
class MealController < ApplicationController
  before_action :authenticate_user!
  before_action :check_correct_user!

  def show
    @meal = current_user.meals.last
  end

  private

  def check_correct_user!
    unless current_user.id == params[:id].to_i
      head(403)
    end
  end
end

app/controllers/preference_controller.rb
class PreferenceController < ApplicationController
  before_action :authenticate_user!
  before_action :check_correct_user!

  ACCEPTABLE_PREFERENCE_ATTRIBUTES = [:chicken, :mutton, :beef, :fish, :prawn, :squid]

  def new
    unless current_user.preference
      current_user.preference = Preference.create
    end
    redirect_to preference_edit_user_path
  end

  def edit
    unless current_user.preference
      return redirect_to preference_new_user_path
    end

    @preference = current_user.preference
  end

  def update
    unless current_user.preference
      return redirect_to preference_new_user_path
    end

    if current_user.preference.update!(params[:preference].permit(ACCEPTABLE_PREFERENCE_ATTRIBUTES))
      flash[:notice] = 'Preference updated'
    end

    redirect_to preference_edit_user_path
  end

  private

  def check_correct_user!
    unless current_user.id == params[:id].to_i
      head(403)
    end
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/index.html.erb
<div class="container-fluid">
  <div class="jumbotron">
    <h1>Welcome to food for the heart</h1>
    <p>We assign you food from the bottom of our heart, according to your likings.</p>
    <p>
      <% if user_signed_in? %>
        <%= link_to('Meal Preference', preference_new_user_path(current_user.id), :class => 'btn btn-primary btn-lg') %>
      <% else %>
        <%= link_to('Login', new_user_session_path, :class => 'btn btn-primary btn-lg') %>
      <% end %>
      <%= link_to('Assign Meals', meal_assignment_index_path, :class => 'btn btn-primary btn-lg') %>
    </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodForTheHeart</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to('Food for the heart', root_path, :class => 'navbar-brand') %>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
                <li><%= link_to('Meal Preference', preference_new_user_path(current_user.id)) %></li>
                <li><%= link_to('Meal for the day', meal_show_user_path(current_user.id)) %></li>
            <% else %>
                <li><a href="#">Assign meals</a></li>
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
                <p class="navbar-text">Signed in as <%= current_user.email %></p>
                <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
            <% else %>
                <li>
                  <%= link_to('Login', new_user_session_path) %>
                </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <% if alert %>
      <div class="container-fluid">
        <div class="alert alert-danger" role="alert"><%= alert %></div>
      </div>
    <% end %>
    <% if notice %>
      <div class="container-fluid">
        <div class="alert alert-info notice" role="alert"><%= notice %></div>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/meal/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6">
      <h1>Assigned Meal</h1>
      <% if @meal %>
        <h3><%= @meal.meal_type.capitalize %></h3>
        <p>Assigned at <%= @meal.meal_availability.availability_for %></p>
      <% else %>
        <h3>Not assigned</h3>
      <% end %>
    </div>
  </div>
</div>

app/views/meal_assignment/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6">
      <h1>Meal Availability</h1>
      <table class="table table-striped">
        <tr>
          <th>Type</th>
          <th>Availability</th>
        </tr>
        <tr><td>Chicken</td><td><%= @meal_availability.chicken %></td></tr>
        <tr><td>Mutton</td><td><%= @meal_availability.mutton%></td></tr>
        <tr><td>Beef</td><td><%= @meal_availability.beef %></td></tr>
        <tr><td>Fish</td><td><%= @meal_availability.fish %></td></tr>
        <tr><td>Prawn</td><td><%= @meal_availability.prawn %></td></tr>
        <tr><td>Squid</td><td><%= @meal_availability.squid %></td></tr>
        <tr><td>Total</td><td><%= @meal_availability.total %></td></tr>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <h1>Meal Assignment</h1>
      <table class="table table-striped">
        <tr>
          <th>Meal Type</th>
          <th>User</th>
        </tr>
        <% @meal_availability.meals.each do |meal| %>
            <tr><td><%= meal.meal_type.capitalize %></td><td><%= meal.user.email %></td></tr>
        <%end %>
      </table>
    </div>
  </div>
</div>

app/views/preference/edit.html.erb
<%= form_for @preference, url: preference_update_user_path, method: 'put' do |f| %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-1">
        Meat:
      </div>
      <div class="col-md-1">
        <%= f.label :chicken %>
        <%= f.check_box :chicken %>
      </div>
      <div class="col-md-1">
        <%= f.label :mutton %>
        <%= f.check_box :mutton %>
      </div>
      <div class="col-md-1">
        <%= f.label :beef %>
        <%= f.check_box :beef %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-1">
        Seafood:
      </div>
      <div class="col-md-1">
        <%= f.label :fish %>
        <%= f.check_box :fish %>
      </div>
      <div class="col-md-1">
        <%= f.label :prawn %>
        <%= f.check_box :prawn %>
      </div>
      <div class="col-md-1">
        <%= f.label :squid %>
        <%= f.check_box :squid %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-1">
        <%= f.submit :class => 'btn btn-default' %>
      </div>
    </div>
  </div>
<% end %>

app/views/user/index.html.erb
<div class="container-fluid">
  <div class="jumbotron">
    <h1>Welcome <%= current_user.email %></h1>
    <p>Here, please tell us what you like!</p>
    <p>
      <%= link_to('Meal Preference', preference_new_user_path(current_user.id), :class => 'btn btn-primary btn-lg') %>
      <%= link_to('Meal for the day', root_path, :class => 'btn btn-primary btn-lg') %>
    </p>
  </div>
</div>